# Generated by Django 4.2.11 on 2024-04-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='task.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128)),
                ('task_description', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('updated', 'Updated'), ('overdue', 'Overdue'), ('done', 'Done')], default='to_do', max_length=10)),
                ('type', models.CharField(choices=[('single', 'Single'), ('recurring', 'Recurring')], default='single', max_length=10)),
                ('category', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'normal'), ('special', 'special')], default='normal', max_length=10)),
                ('due_date', models.DateTimeField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(blank=True)),
                ('completed_date', models.DateTimeField(blank=True)),
                ('rooms', models.ManyToManyField(related_name='tasks', to='task.room')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='task.workspace'),
        ),
    ]
