# Generated by Django 4.2.11 on 2024-04-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_workspace_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='description',
        ),
    ]
