# Generated by Django 4.2.11 on 2024-04-09 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_remove_workspace_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(related_name='workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
