# Generated by Django 4.2.11 on 2024-04-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_workspace_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
