# Generated by Django 4.2.11 on 2024-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_completed_date_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
