# Generated by Django 4.2.11 on 2024-05-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_floor_icon_room_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='color',
            field=models.CharField(default='#8A2BE2', max_length=7),
        ),
    ]
