# Generated by Django 4.2.11 on 2024-07-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_deleted_date'),
        ('task', '0010_update_site_name'),
    ]

    operations = [
    ]
