# Generated by Django 4.2.11 on 2024-04-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_workspace_users'),
        ('users', '0002_user_default_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.workspace', verbose_name='Default workspace'),
        ),
    ]
